language: shell
matrix:
  fast_finish: true
  include:
    - os: windows
      before_script:
        - powershell -Command 'Set-ExecutionPolicy Unrestricted'
        - powershell -File ./Invoke-Setup.ps1
      script:
        - powershell -File ./build.ps1 -CI -Test -Tags 'Remote' -Exclude 'LinuxOnly'