language: shell
matrix:
  fast_finish: true
  include:
    - os: windows
      before_script:
        - powershell -Command 'Set-ExecutionPolicy Unrestricted'
        - powershell -Command 'Import-Module -Name PowerShellGet'
        - powershell -Command 'Install-Module -Name Pester -SkipPublisherCheck -RequiredVersion 5.0.4 -Scope CurrentUser -Force'
        - powershell -Command 'Install-Module -Name BuildHelpers -Scope CurrentUser -Force'
        - powershell -Command 'Import-Module -Name Pester'
        - powershell -Command 'Import-Module -Name BuildHelpers'
      script:
        - powershell -File ./build.ps1 -Test -CI -Exclude 'Intense'
        - bash <(curl -s https://codecov.io/bash) -f coverage.xml
    - os: linux
      dist: trusty
      sudo: false
      addons:
        apt:
          sources:
            - sourceline: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/14.04/prod trusty main"
              key_url: "https://packages.microsoft.com/keys/microsoft.asc"
          packages:
            - powershell
      before_script:
        - pwsh -Command 'Import-Module -Name PowerShellGet'
        - pwsh -Command 'Install-Module -Name Pester -SkipPublisherCheck -RequiredVersion 5.0.4 -Scope CurrentUser -Force'
        - pwsh -Command 'Install-Module -Name BuildHelpers -Scope CurrentUser -Force'
        - pwsh -Command 'Import-Module -Name Pester'
        - pwsh -Command 'Import-Module -Name BuildHelpers'
      script:
        - pwsh -File ./build.ps1 -Test -CI -Exclude 'Intense'