language: shell
matrix:
  fast_finish: true
  include:
    - os: windows
      before_script:
        - powershell -File ./Invoke-Setup.ps1
      script:
        - powershell -File ./build.ps1 -Test -CI -Tags 'Remote' -Exclude 'LinuxOnly'
        - bash <(curl -s https://codecov.io/bash) -f coverage.xml
    - os: linux
      dist: trusty
      sudo: false
      addons:
        apt:
          sources:
            - sourceline: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/14.04/prod trusty main"
              key_url: "https://packages.microsoft.com/keys/microsoft.asc"
          packages:
            - powershell
      before_script:
        - pwsh -File ./Invoke-Setup.ps1
      script:
        - pwsh -File ./build.ps1 -Test -CI -Tags 'Remote' -Exclude 'WindowsOnly'