language: shell
matrix:
  fast_finish: true
  include:
    - os: windows
      before_script:
        - powershell -Command 'Set-ExecutionPolicy Unrestricted'
        - powershell -File ./Invoke-Setup.ps1
      script:
        - powershell -File ./build.ps1 -Test -CI -Tags 'Remote' -Exclude 'LinuxOnly'
        - bash <(curl -s https://codecov.io/bash) -f coverage.xml