version: 1.0.{build}

image:
  - Visual Studio 2017
  - Visual Studio 2019

platform:
  - Any CPU

matrix:
  fast_finish: true

install:
  - ps: ./Invoke-Setup.ps1
  - ps: dotnet tool install --global Codecov.Tool

build_script:
  - ps: ./build.ps1 -Lint -CI

test_script:
  - ps: ./build.ps1 -CI -Test -Tags 'Remote' -Exclude 'LinuxOnly' -WithCoverage
  
after_test:
  - ps: codecov -f "**/coverage.xml" -t $Env:CODECOV_TOKEN